# docker plugin install  grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
# docker plugin enable loki

x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}.\d{3}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<date>\d{4}-\d{2}-\d{2}) (?P<time>\d{2}:\d{2}:\d{2}.\d{3}) (?P<message>(?s:.*))$$'

services:

  db:
    image: postgres:16
    networks:
      - backend
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=core_user
      - POSTGRES_PASSWORD=core_pwd
    ports:
      - "5432:5432"
    logging: *default-logging

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - backend
    logging: *default-logging

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - backend
    healthcheck:
      test: nc -z kafka 9092
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10
    logging: *default-logging

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend
    logging: *default-logging

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - backend
    logging: *default-logging

  # Infrastructure
  loki:
    image: grafana/loki:3.0.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  prometheus:
    image: prom/prometheus:v2.51.2
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging
    networks:
      - infrastructure

  tempo:
    image: grafana/tempo:2.4.1
    hostname: tempo
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "14250:14250"
      - "4317:4317"
    depends_on:
      - loki
    networks:
      - infrastructure
    logging: *default-logging

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3200:3000"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    networks:
      - infrastructure
    logging: *default-logging

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    hostname: otel-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./etc/otel-collector/config.yaml:/etc/otel-collector-config.yaml
    networks:
      - infrastructure

  api-cdt-gateway-service:
    image: agusramdan/api-cdt-gateway-service:dev
    container_name: api-cdt-gateway-service
    depends_on:
      - mongodb
#    env_file:
#      - ./docker/dev/gateway.env
    environment:
      - SERVER_PORT=8097
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8097:8097"
    networks:
      - backend

  api-cdt-core-service:
    build: .
    #image: agusramdan/api-cdt-core-service:dev
    container_name: api-cdt-core-service
    environment:
      - SPRING_PROFILES_ACTIVE=devdocker,itsjeck
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317 # send traces to Tempo
#      - OTEL_SERVICE_NAME=api-cdt-core-service # service name for Span
#      - OTEL_RESOURCE_ATTRIBUTES=compose_service=api-cdt-core-service # add custom resource attribute to Span for Grafana Trace to Logs feature
#      - OTEL_METRICS_EXPORTER=none # disable metrics exporter
    ports:
      - "8082:8080"
    depends_on:
      - db
      - kafka
      - loki
      - tempo
    networks:
      - infrastructure
      - backend
      - core
      - frontend

  api-cdt-cdm-service:
    image: agusramdan/api-cdt-cdm-service:dev
#    build:
#      context: .
    container_name: api-cdt-cdm-service
#    labels:
#      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - mongodb
#    env_file:
#      - ./gateway.env
    environment:
      - SPRING_PROFILES_ACTIVE=oauth2,devdocker,dev
    ports:
      - "8091:8080"
    networks:
      - backend
      - core
      - frontend

networks:
  frontend:
    driver: bridge
  core:
    driver: bridge
  backend:
    driver: bridge
  kafka:
    driver: bridge
  keycloak:
    driver: bridge
  infrastructure:
    driver: bridge