
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=core
      - POSTGRES_USER=core_user
      - POSTGRES_PASSWORD=core_pwd
    ports:
      - "5432:5432"
    volumes:
      - pg-16-data:/var/lib/postgresql/data

  api-cdt-core-trx-service:
    image: 'api-cdt-core-trx-service'
    container_name: api-cdt-core-trx-service
    environment:
      - SPRING_PROFILES_ACTIVE=devdocker,local
      - JAVA_OPTS="-Xms128M -Xmx128M"
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8082:8080"
    depends_on:
        - db

volumes:
  pg-16-data: