---
# JVM memory settings
jvm:
  initial-heap-size: 256m
  max-heap-size: 512m

server:
  port: 8080
  error:
    include-stacktrace: never

---
spring:
  application:
    name: api-cdt-core-service
  threads:
    virtual:
      enabled: true
  thread-executor: virtual

  config:
    use-legacy-processing: true
  jmx:
    enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://db:5432/core
    username: core_user
    password: core_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate.ddl-auto: update

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: core-callback-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "agus.ramdan.*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    admin:
      auto-create-topics: true

