management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans
    endpoint: http://tempo:9411/api/v2/spans
#logging:
#  level:
#    root: WARN
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%t] %-5level %logger{36} - %msg%n"
