global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'api-cdt-core-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-cdt-core-service:7180']
  - job_name: 'api-cdt-cdm-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-cdt-cdm-service:7180']
